# Generated by Django 6.0.3 on 2026-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('food', 'غذا و نوشیدنی'), ('nature', 'طبیعت و کوهنوردی'), ('culture', 'گردشگری فرهنگی'), ('adventure', 'ماجراجویی'), ('art', 'عکاسی و هنر')], max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='experiences/')),
                ('provider_name', models.CharField(max_length=150)),
                ('rating', models.FloatField(default=0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
