# Generated by Django 6.0.3 on 2026-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='mizbanuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/mizbans/', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='visitoruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/visitors/', verbose_name='تصویر پروفایل'),
        ),
    ]
