from django.urls import path
from .views import (ExperienceListView, ExperienceDetailView,
                    ExperienceCreateView, ExperienceImageUploadAPIView,
                    ExperienceUpdateView, ExperienceImageDeleteView,
                    MyExperienceView, RateExperienceView,
                    GetRateExperienceView, ToggleFavoriteView,
                    FavoriteExperiencesListView, CommentListCreateView,
                    CommentDeleteView, ProviderStatsView,
                    ExperienceDeleteView, AdminExperienceListView,
                    AdminExperienceStatusUpdateView, AdminUserListView, AdminCommentListView, AdminCommentDeleteView,
                    AllExperienceAPIView, BookingCreateAPIView, request_payment, verify_payment, )


urlpatterns = [
    path("experiences/", ExperienceListView.as_view(), name="experience-list"),
    path("experiences/create/", ExperienceCreateView.as_view(), name="experience-create"),
    path("experiences/<int:id>/", ExperienceDetailView.as_view(), name="experience-detail"),
    path("allexperiences/<int:id>/", AllExperienceAPIView.as_view(), name="allexperience-detail"),
    path("experiences/<int:pk>/upload-image/", ExperienceImageUploadAPIView.as_view(), name="experience-image-upload"),
    path("experiences/<int:pk>/update/", ExperienceUpdateView.as_view(), name="experience-update"),
    path("experiences/images/<int:pk>/delete/",ExperienceImageDeleteView.as_view(),name="experience-image-delete"),
    path("experiences/me/", MyExperienceView.as_view(), name="experience-me"),
    path("experiences/<int:experience_id>/rate/", RateExperienceView.as_view(), name="experience-rate"),
    path("experiences/<int:experience_id>/get-rate/", GetRateExperienceView.as_view(), name="experience-get-rate"),
    path('experiences/<int:pk>/favorite/', ToggleFavoriteView.as_view(), name='toggle-favorite'),
    path('favorites/', FavoriteExperiencesListView.as_view(), name='favorite-list'),
    path('experiences/<int:experience_id>/comments/', CommentListCreateView.as_view(), name='experience-comments'),
    path('comments/<int:pk>/', CommentDeleteView.as_view(), name='delete-comment'),
    path('profile/stats/', ProviderStatsView.as_view(), name='provider-stats'),
    path("experiences/<int:pk>/delete/", ExperienceDeleteView.as_view(), name="experience-delete"),
    path("admin-api/experiences/", AdminExperienceListView.as_view(), name="admin-experience-list"),
    path("admin-api/experiences/<int:pk>/status/", AdminExperienceStatusUpdateView.as_view(), name="admin-experience-status"),
    path("admin-api/users/", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin-api/comments/", AdminCommentListView.as_view(), name="admin-comment-list"),
    path("admin-api/comments/<int:pk>/", AdminCommentDeleteView.as_view(), name="admin-comment-delete"),
    path('bookings/', BookingCreateAPIView.as_view(), name='create_booking'),
    path('bookings/request-payment/', request_payment, name='request_payment'),
    path('bookings/verify-payment/', verify_payment, name='verify_payment'),
]