# Generated by Django 6.0.3 on 2026-04-10 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('food', 'غذا و نوشیدنی'), ('nature', 'طبیعت و کوهنوردی'), ('culture', 'گردشگری فرهنگی'), ('adventure', 'ماجراجویی'), ('art', 'عکاسی و هنر')], max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='experiences/')),
                ('rating', models.FloatField(default=0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
