# Generated by Django 6.0.3 on 2026-04-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0002_experience_address_experience_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
