# Generated by Django 6.0.3 on 2026-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0004_remove_experience_image_experienceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('غذا و نوشیدنی', 'غذا و نوشیدنی'), ('طبیعت و کوهنوردی', 'طبیعت و کوهنوردی'), ('گردشگری فرهنگی', 'گردشگری فرهنگی'), ('ماجراجویی', 'ماجراجویی'), ('عکاسی و هنر', 'عکاسی و هنر')], max_length=50),
        ),
    ]
