# Generated by Django 6.0.3 on 2026-04-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0005_alter_experience_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='total_ratings',
        ),
    ]
