# Generated by Django 6.0.3 on 2026-04-20 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0007_experienceratingmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
