# Generated by Django 6.0.3 on 2026-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='pending', max_length=20),
        ),
    ]
