# Generated by Django 6.0.3 on 2026-05-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizback', '0011_booking_authority_booking_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='paid', max_length=20),
        ),
    ]
